                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /home/dgomes/software/gmx2019.3/bin/gmx
Data prefix:  /home/dgomes/software/gmx2019.3
Working dir:  /home/dgomes/water_md/opc
Command line:
  gmx mdrun -deffnm eql


Back Off! I just backed up eql.log to ./#eql.log.1#
Reading file eql.tpr, VERSION 2019.3 (single precision)
Changing nstlist from 10 to 40, rlist from 1.01 to 1.117

Using 1 MPI thread
Using 8 OpenMP threads 


Back Off! I just backed up eql.xtc to ./#eql.xtc.1#

Back Off! I just backed up eql.edr to ./#eql.edr.1#
starting mdrun 'opc in water'
50000 steps,    100.0 ps.

Writing final coordinates.

Back Off! I just backed up eql.gro to ./#eql.gro.1#

               Core t (s)   Wall t (s)        (%)
       Time:      789.450       98.682      800.0
                 (ns/day)    (hour/ns)
Performance:       87.555        0.274

GROMACS reminds you: "You Fill Me With Inertia" (The Long Blondes)

