                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /home/dgomes/software/gmx2019.3/bin/gmx
Data prefix:  /home/dgomes/software/gmx2019.3
Working dir:  /home/dgomes/water_md/tip5p
Command line:
  gmx mdrun -deffnm min


Back Off! I just backed up min.log to ./#min.log.2#
The current CPU can measure timings more accurately than the code in
gmx mdrun was configured to use. This might affect your simulation
speed as accurate timings are needed for load-balancing.
Please consider rebuilding gmx mdrun with the GMX_USE_RDTSCP=ON CMake option.
Reading file min.tpr, VERSION 2019.3 (single precision)

Using 1 MPI thread
Using 8 OpenMP threads 


Back Off! I just backed up min.trr to ./#min.trr.2#

Back Off! I just backed up min.edr to ./#min.edr.2#

Steepest Descents:
   Tolerance (Fmax)   =  1.00000e+01
   Number of steps    =         1000

Step 9, time 0.009 (ps)  LINCS WARNING
relative constraint deviation after LINCS:
rms 0.004024, max 0.098595 (between atoms 4286 and 4287)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
   4286   4287   39.4    0.0975   0.0863      0.0957
   4286   4288   32.8    0.0969   0.0863      0.0957

Step 12, time 0.012 (ps)  LINCS WARNING
relative constraint deviation after LINCS:
rms 0.001385, max 0.035129 (between atoms 4286 and 4287)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length

Energy minimization reached the maximum number of steps before the forces
reached the requested precision Fmax < 10.

writing lowest energy coordinates.

Back Off! I just backed up min.gro to ./#min.gro.2#

Steepest Descents did not converge to Fmax < 10 in 1001 steps.
Potential Energy  = -4.5386180e+04
Maximum force     =  1.4950388e+02 on atom 2308
Norm of force     =  7.6946497e+00

GROMACS reminds you: "The Wheels On the Bus Go Round and Round" (J. Richman)

