                      :-) GROMACS - gmx mdrun, 2019.3 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2018, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2019.3
Executable:   /home/dgomes/software/gmx2019.3/bin/gmx
Data prefix:  /home/dgomes/software/gmx2019.3
Working dir:  /home/dgomes/water_md/spce
Command line:
  gmx mdrun -deffnm min


Back Off! I just backed up min.log to ./#min.log.4#
The current CPU can measure timings more accurately than the code in
gmx mdrun was configured to use. This might affect your simulation
speed as accurate timings are needed for load-balancing.
Please consider rebuilding gmx mdrun with the GMX_USE_RDTSCP=ON CMake option.
Reading file min.tpr, VERSION 2019.3 (single precision)

Using 1 MPI thread
Using 8 OpenMP threads 


Back Off! I just backed up min.trr to ./#min.trr.3#

Back Off! I just backed up min.edr to ./#min.edr.3#

Steepest Descents:
   Tolerance (Fmax)   =  1.00000e+01
   Number of steps    =         1000

Step 10, time 0.01 (ps)  LINCS WARNING
relative constraint deviation after LINCS:
rms 0.001786, max 0.035196 (between atoms 625 and 627)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
    625    626   40.3    0.1000   0.0994      0.1000
    625    627   34.5    0.1000   0.0965      0.1000
   1081   1082   40.8    0.1000   0.1018      0.1000
   1081   1083   33.8    0.1000   0.1023      0.1000

Step 18, time 0.018 (ps)  LINCS WARNING
relative constraint deviation after LINCS:
rms 0.001456, max 0.043799 (between atoms 1951 and 1952)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
   1951   1952   35.0    0.0978   0.1044      0.1000
   1951   1953   35.7    0.0978   0.1043      0.1000

Step 19, time 0.019 (ps)  LINCS WARNING
relative constraint deviation after LINCS:
rms 0.000894, max 0.026697 (between atoms 1951 and 1953)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
   1951   1952   37.0    0.1044   0.0974      0.1000
   1951   1953   37.5    0.1043   0.0973      0.1000

Step 20, time 0.02 (ps)  LINCS WARNING
relative constraint deviation after LINCS:
rms 0.004376, max 0.130215 (between atoms 1951 and 1953)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
   1951   1952   53.6    0.0974   0.1130      0.1000
   1951   1953   53.6    0.0973   0.1130      0.1000

Step 21, time 0.021 (ps)  LINCS WARNING
relative constraint deviation after LINCS:
rms 0.003446, max 0.082643 (between atoms 2194 and 2196)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
   1723   1724   38.9    0.1000   0.1073      0.1000
   1723   1725   47.3    0.1000   0.1058      0.1000
   1951   1952   36.1    0.1130   0.0977      0.1000
   1951   1953   32.9    0.1130   0.0981      0.1000
   2194   2195   50.0    0.1000   0.0932      0.1000
   2194   2196   45.2    0.1000   0.0917      0.1000

Step 23, time 0.023 (ps)  LINCS WARNING
relative constraint deviation after LINCS:
rms 0.002496, max 0.059685 (between atoms 1723 and 1725)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
   1723   1725   34.3    0.1007   0.0940      0.1000
   2194   2195   36.4    0.0992   0.1034      0.1000
   2194   2196   33.8    0.0990   0.1037      0.1000

Step 28, time 0.028 (ps)  LINCS WARNING
relative constraint deviation after LINCS:
rms 0.002888, max 0.076890 (between atoms 1798 and 1800)
bonds that rotated more than 30 degrees:
 atom 1 atom 2  angle  previous, current, constraint length
   1798   1800   37.1    0.1010   0.0923      0.1000

Energy minimization reached the maximum number of steps before the forces
reached the requested precision Fmax < 10.

writing lowest energy coordinates.

Back Off! I just backed up min.gro to ./#min.gro.3#

Steepest Descents did not converge to Fmax < 10 in 1001 steps.
Potential Energy  = -5.0016871e+04
Maximum force     =  7.3341545e+01 on atom 371
Norm of force     =  6.2518134e+00

GROMACS reminds you: "The soul? There's nothing but chemistry here" (Breaking Bad)

